hmcts/sscs-case-loader

Jenkinsfile_CNP, build.gradle, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf, src/main/resources/application.yaml, web.config
=> SSCS-2557 Added CNP Infrastructure code and Jenkinsfile

Jenkinsfile_parameterized, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf, src/main/resources/application.yaml, web.config
=> SSCS-2557 Added the latest infrastructure code

README.md
No tickets
Add CCD dockerised env documentation
```
[ ] Yes
[ x] No
```
=> Add CDD dockerised env documentation in the README

build.gradle, web.config
=> Removed the version number from app jar name

config/checkstyle/checkstyle.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CoreCddCaseDataServiceIntegrationTest.java, src/e2e/java/uk.gov.hmcts.reform.sscs/RetrieveFileFromSftpService.java, src/e2e/java/uk.gov.hmcts.reform.sscs/SaveSimpleCaseIntoCcd.java, src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/AppealCases.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformJsonCasesToCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/FetchXmlFilesService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/SftpFetchXmlFilesImpl.java, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/XmlValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/utils/FileUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/models/CaseDataContentToJsonTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CoreCaseDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformJsonCasesToCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformXmlFilesToJsonFilesTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/xml/SftpFetchXmlFilesServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/xml/XmlErrorHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/utils/FileUtilsTest.java
- Change order of import statements to match Tribunals
- Ignore starred imports
=> Checkstyle changes

infrastructure/main.tf
=> Fixed the syntax error in main.tf

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
Enhance IT to mock external services rather than our internal ones. 
```
[ ] Yes
[ x] No
```
=> Mock idam authentication otherwise it fails

README.md
https://tools.hmcts.net/jira/browse/SSCS-2693
Update readme with the instructions to setup the docker container. 
```
[ x] Yes
[ ] No
```
=> SSCS-2693 Update readme to use SSCS docker container

infrastructure/main.tf, infrastructure/variables.tf
=> Sscs 2697 configure env variables

infrastructure/variables.tf
=> SSCS-2697 Removed unused infrastructure variables

infrastructure/main.tf
=> Double closing brackets to resolve sftp and other var issues

src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshServiceTest.java
=> SSCS-2759 Added code to handle sftp key as byte stream

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-2769
Configure logging
```
[ ] Yes
[ x] No
```
=> SSCS-2769 Configure logging in CNP and in the application

src/e2e/java/uk.gov.hmcts.reform.sscs/RetrieveFileFromSftpService.java, src/main/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderScheduler.java
No Jira
Configure conditional on the scheduler so that it does not clash with the tests.
```
[ ] Yes
[ x] No
```
=> Disable Scheduler when tests run because otherwise it starts

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CoreCaseDataService.java
https://tools.hmcts.net/jira/browse/SSCS-2769
Add more logs to get more details and update CCD url.
```
[ ] Yes
[ x] No
```
=> Update CCD url

infrastructure/main.tf
=> Move to http protocol

src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshService.java, src/main/resources/application.yaml
Add more logs
```
[ ] Yes
[ ] No
```
=> SSCS-2612 Add more logs

infrastructure/main.tf
=> subscription and is_frontend added

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/properties/CoreCaseDataPropertiesTest.java, src/main/java/uk/gov/hmcts/reform/sscs/config/properties/CoreCaseDataProperties.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CreateCoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CreateCoreCaseDataServiceTest.java
=> Improve logs to debug caseloader in CNP

src/test/resources/CaseDataArray.json, src/test/resources/CaseDataArrayWithOptionalFields.json
=> Add dates in json file to test correct sorting order

src/main/java/uk/gov/hmcts/reform/sscs/models/GapsEvent.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/CaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformJsonCasesToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/resources/CaseDataArrayWithUpdates.json
- Find the latest event on a case
- Use this to send the correct eventType to CCD
- Add missing unit tests for each update event
=> Update CCD with latest event type

infrastructure/sandbox.tfvars
=> Turn on debug level logs in sandbox

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
- Send an evidence received event if a new evidence is in the case
- Compare the previous version of the case from CCD with the new version
=> SSCS-2758 Evidence received event

src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataRepository.java, src/main/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataService.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataRepositoryTest.java
=> SSCS-2775 [AS] Fix for codacy checks.

infrastructure/prod.tfvars, src/test/java/uk/gov/hmcts/reform/sscs/scheduler/CronExpressionProductionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderSchedulerTest.java
=> SSCS-2765 Added Cron scheduler to PROD environment

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/TransformJsonCasesToCaseDataTest.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/AppealCase.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/Hearing.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/MajorStatus.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/Parties.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/Appellant.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformJsonCasesToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/resources/CaseDataArray.json, src/test/resources/CaseDataArrayWithOptionalFields.json, src/test/resources/CaseDataArrayWithUpdates.json, src/test/resources/CaseDataContent.json, src/test/resources/SSCS_Extract_Delta_2017-05-24-16-14-19.json, src/test/resources/SSCS_Extract_Delta_2017-05-24-16-14-19.xml
- Allow multiple Parties
- Allow multiple Hearings
- Allow multiple FurtherEvidence
- Remove postcodes from appellants
- Do not create cases if they already exist in CCD
- Only use Party with Role ID 4 to build appellant details
=> SSCS-2818 Fix issues from performance test

src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/resources/CaseDataContent.json
Case loader was only processing the last cases. This small PR fixes this
=> No longer overwriting cases before they are processed

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/e2e/java/uk.gov.hmcts.reform.sscs/ProcessFileAndSaveIntoCcd.java, src/e2e/java/uk.gov.hmcts.reform.sscs/SaveAndUpdateSimpleCaseInCcd.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/CaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/services/date/DateHelper.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
- Add config to only import cases created after this date
=> SSCS-2825 Ignore cases created before date

build.gradle
=> added test:smoke task for case-loader

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CoreCddCaseDataServiceTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/MockCcdIdamServices.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/java/uk/gov/hmcts/reform/sscs/config/properties/SftpSshProperties.java, src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshServiceTest.java
=> SSCS-2823 [AS] SFTP tools to move processed files.

infrastructure/variables.tf
=> Added missing vars to variables.tf

Jenkinsfile_CNP
=> Cert instead of key for key files

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/XmlValidatorTest.java, src/e2e/java/uk.gov.hmcts.reform.sscs/RetrieveFileFromSftpService.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/SftpCustomException.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapter.java, src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/XmlValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapterTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpSshServiceTest.java
=> SSCS-2823 [AS] Wrap JSch functionality to simplify processing.

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controllers/SmokeTest.java
=> test improvement

build.gradle, docker/sftp/data/incoming/SSCS_Extract_Delta_SmokeTest_2018-03-15-16-14-19.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controllers/SmokeTest.java, src/e2e/java/uk.gov.hmcts.reform.sscs/functional/ProcessFileAndSaveIntoCcd.java, src/e2e/java/uk.gov.hmcts.reform.sscs/functional/RetrieveFileFromSftpService.java, src/e2e/java/uk.gov.hmcts.reform.sscs/functional/SaveAndUpdateSimpleCaseInCcd.java, src/e2e/java/uk.gov.hmcts.reform.sscs/smoke/GetSavedCase.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/smoke/test/Smoke.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/resources/application.yaml
=> Added smoke tests

Jenkinsfile_CNP
=> Temp disable loading vaults on master as it is experimental feature

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
=> Revert all az vault to master changes

infrastructure/output.tf
=> remove output.tf

infrastructure/main.tf, infrastructure/variables.tf
=> Experimental feature to run one instance only

src/e2e/java/uk.gov.hmcts.reform.sscs/smoke/GetSavedCase.java
=> removed spring context for smoke tests

src/e2e/java/uk.gov.hmcts.reform.sscs/smoke/GetSavedCase.java
=> fix ssl issue in smoke tests

infrastructure/aat.tfvars, infrastructure/sandbox.tfvars
=> Restore default app logging levels

src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/Doc.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataService.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataServiceTest.java, src/test/resources/CaseDataContent.json, src/test/resources/CaseDetailsWithOneEvidenceAndOneEvent.json
- Add evidence type and evidence provided by variables
- Get mappings for these fields from reference data
- Remove description variable
=> SSCS-2888 Further evidence changes

src/main/java/uk/gov/hmcts/reform/sscs/controller/RootController.java, src/main/java/uk/gov/hmcts/reform/sscs/controller/smoke/test/Smoke.java, src/test/java/uk/gov/hmcts/reform/sscs/controller/RootControllerTest.java
- Return 200 when azure application hits the / endpoint every few seconds polluting the logs
=> SSCS-2899 Add Root Controller

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/AppealCase.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java
=> SSCS-2904 [AS] Calculate the benefit type code (PIP,ESA, etc)

src/e2e/java/uk.gov.hmcts.reform.sscs/smoke/GetSavedCase.java
No ticket
Fix to run smoke tests on all env including Production
```
[ ] Yes
[ x] No
```
=> Fix to deploy to production

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/UpdateCcdServiceRetryAndRecoverTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CreateCcdService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/StartEventCcdService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdService.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdServiceTest.java, src/test/resources/CaseDataContent.json, src/test/resources/Subscriptions.json
- Ensure the correct CCD endpoint is hit when starting an update event
=> Update event fix

src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataServiceTest.java
No Jira
In case BenefitType cannot be found catch the error and return ERR instead so that we can continue processing cases.
```
[ ] Yes
[x ] No
```
=> Benefit type is not found then return ERR

src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapter.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapterTest.java
=> SSCS-2921 [AS] Sort files from SFTP.

infrastructure/prod.tfvars
=> Prod Release

src/main/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderScheduler.java
=> log info for the http.host

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-2932
Use WEBSITE_HOSTNAME instead of HTTP_HOST
```
[ ] Yes
[ ] No
```
=> Use WEBSITE_HOSTNAME instead of HTTP_HOST

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderSchedulerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderScheduler.java, src/main/resources/application.yaml
=> Better naming for vars conditional fix

infrastructure/prod.tfvars
=> Proper cron settings to run on prod

build.gradle
=> Fixed dependencyCheck build issue

infrastructure/main.tf
=> fix to failures

README.md
No ticket
Update readme to include the new github public sscs-docker repo.
```
[ ] Yes
[x ] No
```
=> udpate readme to use the github public sscs-docker repo

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/FailedXmlFileException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/GapsValidationException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/JsonMapperErrorException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/SftpCustomException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/TransformException.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java
=> minor refactor to remove log error when thowing exceptions

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderSchedulerTest.java, src/main/java/uk/gov/hmcts/reform/sscs/scheduler/SscsCaseLoaderScheduler.java, src/main/resources/application.yaml
=> Check slot with proper variable

src/main/java/uk/gov/hmcts/reform/sscs/services/TransformationService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/TransformationServiceTest.java, src/test/resources/delta_with_no_cases.xml
https://tools.hmcts.net/jira/browse/SSCS-2962
Fix issue with Delta comes with Zero cases.
```
[ ] Yes
[x ] No
```
=> SSCS-2962 Add production and test code when Delta has zero cases

README.md, src/main/resources/application.yaml
NO jira ticket
Update readme with some more details to hopefully make things a bit easier. 
```
[ ] Yes
[ ] No
```
=> Add definition confluence and user to log in CCD UI

README.md
Update the ReadMe instructions to bring it inline with todate changes.
https://tools.hmcts.net/jira/browse/SSCS-2981
=> Sscs 2981 sscs case loader update documentation

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/models/GapsEvent.java
no jira
dependency check fix
```
[ ] Yes
[ ] No
```
=> dependencyCheck fix

build.gradle, dependency-check-suppressions.xml
=> Fix vulnerabilites

infrastructure/prod.tfvars
=> Start at 9AM BST which is 8AM UTC on server

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
=> Initial commit for vault

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/output.tf, infrastructure/vault_config.tf
=> fix to permission

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/Appeal.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/AppealReason.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/AppealReasonDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/AppealReasons.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/DateRange.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/ExcludeDate.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/HearingOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/MrnDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/Representative.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/CaseDataUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/resources/CaseDataContent.json, src/test/resources/CaseDetailsWithHearingOptions.json
DO NOT MERGE THIS PR INTO MASTER WITHOUT ROBINS APPROVAL
Update the domain objects with CCD Def changes.
https://tools.hmcts.net/jira/browse/SSCS-2501
=> SSCS-2501[SA]:update the domain objects with ccd def changes

build.gradle
No Ticket
Enable functional tests
```
[ ] Yes
[ x] No
```
=> enable functional tests

dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/UpdateCcdServiceRetryAndRecoverTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/XmlSchemas.java, src/main/resources/schema/SSCS_Extract_Schema_Delta_0.9.xsd, src/test/java/uk/gov/hmcts/reform/sscs/services/xml/XmlSchemasTest.java
https://tools.hmcts.net/jira/browse/SSCS-3423
Update Delta schema to 0.9 v
```
[ ] Yes
[ x] No
```
=> Delta Schema updated to 0.9

infrastructure/prod.tfvars
No jira
switch it off temporarily for the public beta release 
```
[ ] Yes
[ x] No
```
=> switch off caseloader for the public-beta migration

infrastructure/prod.tfvars
This reverts commit ead13779769e64dbf9caa3b04dc0a151acc76c52.
=> Revert "switch off caseloader for the public-beta migration (#196)"

src/main/java/uk/gov/hmcts/reform/sscs/services/TransformationService.java
=> set log to debug as we can ignore these cases

infrastructure/main.tf
Change group product id so that other devs can add to vault keys
```
[ ] Yes
[ ] No
```
=> Change group with a one that allows changes by other devs

src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/CaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/resources/CaseDetailsWithAppealReceived.json
- When a case only has an update and no new events then update CCD with changes with a caseUpdated event
=> SSCS-2622 Update CCD with changes

infrastructure/main.tf
=> [PREVIEW]test new idam dns in prod

infrastructure/main.tf
This reverts commit 08bb2caef09b11bc653ebe90b952058b85151f18.
```
[ ] Yes
[ ] No
```
=> Revert "test new idam dns in prod (#216)"

docker/sftp/data/incoming/SSCS_Extract_Delta_2018-05-24-16-14-19.xml, docker/sftp/data/incoming/SSCS_Extract_Delta_SmokeTest_2018-03-15-16-14-19.xml
=> [PREVIEW]Add comment in delta files to know what benefit types they belong to

src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/HearingOptions.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataService.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataServiceTest.java
=> [PREVIEW] SSCS-3915 Set hearing options for paper, oral and Domiciliary cases

src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/Appeal.java, src/main/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/HearingType.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/models/serialize/ccd/HearingTypeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java
=> [PREVIEW] SSCS-3958 Added hearingType to the appeal

infrastructure/main.tf, infrastructure/output.tf, infrastructure/vault_config.tf
=> [PREVIEW] SSCS-3782 Deleted generic vault

infrastructure/main.tf, infrastructure/output.tf, infrastructure/vault_config.tf, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
=> SSCS-4013 Do not overwrite SMS subscription

Jenkinsfile_CNP, infrastructure/main.tf
=> [PREVIEW]add test var

infrastructure/vault_config.tf
=> [PREVIEW]add back the vault_config file

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/idam/IdamApiClient.java
=> [PREVIEW] Increase dependency version numbers

src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java
=> [PREVIEW]Fix some PMD issues

src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java
=> [PREVIEW]Remove component scan because of preventing scheduler to be triggered

build.gradle, src/test/resources/CaseDetailsWithHearingOptions.json
=> [PREVIEW] Remove is appointee field

build.gradle
Case loader is logging exception of "Venue could not be mapped to a valid RPC that SSCS knows about"
```
[ ] Yes
[ ] No
```
=> [PREVIEW] SSCS-4266

build.gradle
=> [PREVIEW] SSCS-4266 Case loader is logging exception of "Venue could not be mapped to a valid RPC that SSCS knows about" updated common version

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/java/uk/gov/hmcts/reform/sscs/models/UpdateType.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/resources/CaseDetailsWithSubscriptions.json
=> [PREVIEW] Sscs 4390 fix case update

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
https://tools.hmcts.net/jira/browse/SSCS-4499
Reduce the number of method calls per line so that exceptions can be more easily traced to their source
```
[ ] Yes
[X] No
```
=> SSCS-4499 Break up call trains so exceptions are less ambiguous

infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/SSCS-4499
Make caseloader run every hour.
```
[ ] Yes
[x] No
```
=> SSCS-4499 Make caseloader run on the hour, every hour

infrastructure/main.tf, infrastructure/variables.tf, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseRetryAndRecoveryTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
=> [PREVIEW] Sscs 4815 token expired

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
=> [PREVIEW] SSCS-4866 Unexpected Notifications INC0410790

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentative.java, src/main/java/uk/gov/hmcts/reform/sscs/util/UkMobile.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/UkMobileTest.java
=> [PREVIEW] SSCS-4919 Case Loader Exception (unprocessable entity)

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentative.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java
=> [PREVIEW]Bugfix/sscs 4919

src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java, src/test/resources/AppealCaseWithRepresentative.json
this way it ensure correct mobile number for both create and update cases
```
[ ] Yes
[ ] No
```
=> [PREVIEW]Add mobile number validation when transforming cases because

build.gradle
Added High Wycombe to venues for SL* post codes in sscs-common
This will apply these changes from sscs-common
0.0.130 Added a new venue for 10 existing postcodes to AIR Lookup
0.0.129 SSCS-4930 Add received via field to data utils
0.0.128 SSCS-4658: Check for mobile number
0.0.127 Make appeal number generator static
0.0.126 Move appeal number generator code to common library
=> Added new venue

build.gradle
=> [PREVIEW] SSCS-4950 Hearing booked event with incorrect venue details

README.md, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseRetryAndRecoveryTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/CreateCcdServiceTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseIdRetryAndRecoverTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseRefRetryAndRecoverTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdServiceRetryAndRecoverTest.java, src/e2e/java/uk.gov.hmcts.reform.sscs/functional/ProcessCaseFile.java, src/e2e/java/uk.gov.hmcts.reform.sscs/smoke/GetSavedCase.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml
=> [PREVIEW] SSCS-4347 improve application yaml local config

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseRetryAndRecoveryTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml
=> [PREVIEW] Hotfix/sscs 5153 fix feign empty body post

build.gradle
=> [PREVIEW] add fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentative.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java
=> [PREVIEW] Sscs 5246 representatives tya number changing

Jenkinsfile_nightly, security.sh
=> set up SSCS case loader security scan

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-5219
Update sscs-common library to 0.0.155
```
[ ] Yes
[X] No
```
=> [PREVIEW] SSCS-5219 - update sscs-common library

Dockerfile
Upgrade cnp-java base to the latest
=> [PREVIEW] SSCS-5081 - Upgrade cnp-java base to the latest

build.gradle
Update common version
```
[ ] Yes
[ ] No
```
=> [PREVIEW] SSCS-5430 Venue Address Change (Stoke)

src/e2e/java/uk.gov.hmcts.reform.sscs/functional/ProcessCaseFile.java, src/e2e/resources/config/application_e2e.yaml, src/main/resources/application-local.yaml, src/main/resources/application.yaml
=> [PREVIEW] fix profile configuration

build.gradle
=> [PREVIEW] Sscs 5653 case loader–info requests error

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/Parties.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentative.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateSubscription.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTestHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateSubscriptionTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java, src/test/resources/AppealCaseWithAppointee.json, src/test/resources/AppealCaseWithAppointeeNoEmail.json, src/test/resources/AppealCaseWithAppointeeNoMobile.json, src/test/resources/AppealCaseWithRepresentative.json, src/test/resources/AppealCaseWithRepresentativeNoEmail.json, src/test/resources/AppealCaseWithRepresentativeNoMobile.json
Used PR 383 and ensure subscriptions do not get unsubscribed by gaps
=> [PREVIEW] SSCS-5520 subscriptions must not get unsubscribed by gaps

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
=> [PREVIEW] SSCS-5596 Case loader – Checking for new evidence

build.gradle
=> [PREVIEW] upgrade common library with subscription fix

src/main/java/uk/gov/hmcts/reform/sscs/exceptions/CcdException.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
=> [PREVIEW] SSCS-5650 Case loader – Handle run time errors

Jenkinsfile_CNP
=> try to prefix preview automatically

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-5989
Update sscs-common to include new venues file
```
[ ] Yes
[X] No
```
=> SSCS-5989 - update sscs-common version

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java
https://tools.hmcts.net/jira/browse/SSCS-5722
Normalise nino
```
[ ] Yes
[X] No
```
=> SSCS-5722 - Normalise nino

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6161
Fix build pipeline issue
```
[ ] Yes
[X] No
```
=> SSCS-6161 - fix build pipeline issue

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6071
Update venue data
```
[ ] Yes
[X] No
```
=> SSCS-6071 - update sscs-common version

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpc.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpcTest.java
=> Sscs 6184 case loader regional centre fix

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/SSCS-6378
=> https://tools.hmcts.net/jira/browse/SSCS-6378

build.gradle
=> [PREVIEW] SSCS-6443 Reference data – Update SSCS venue data 27-08-19

build.gradle
=> fix vulnerability

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
https://tools.hmcts.net/jira/browse/SSCS-6476
Update sscs-common candidate version
```
[ ] Yes
[X] No
```
=> SSCS-6476 - update sscs-common version

src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-6550
=> SSCS-6550 UC changes for case loader

infrastructure/prod.tfvars, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantData.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java
=> [PREVIEW] SSCS-6470 Does Case Loader update all NINO fields?

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
https://tools.hmcts.net/jira/browse/SSCS-6287
=> SSCS-6287 Override responseReceived event to case updated if it is rtl

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
=> [PREVIEW] SSCS-6763 Reference data - Broken sscs-venues file

Jenkinsfile_CNP
=> Disable ASE Deployment on AAT

Jenkinsfile_CNP, build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/ProcessCaseFileTest.java, src/main/java/uk/gov/hmcts/reform/sscs/config/CaseLoaderJobConfig.java
Add "Appeal to proceed" and "Provide information" as a "Direction Type" in the "Issue Direction" event
=> SSCS-6669 - add DirectionType

src/main/java/uk/gov/hmcts/reform/sscs/services/xml/XmlSchemas.java, src/main/resources/schema/SSCS_Extract_Schema_0.10.xsd
=> Sscs 6849 change latest xsd

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/xml/XmlValidator.java
=> Sonar fix external entity processing

src/main/resources/schema/SSCS_Extract_Schema_0.10.xsd
=> Order of element has changed, updated latest xsd

charts/sscs-case-loader/Chart.yaml, charts/sscs-case-loader/requirements.yaml
=> bumping base chart

charts/sscs-case-loader/Chart.yaml, charts/sscs-case-loader/values.yaml
=> JobKind was changed in job chart recently which is breaking case loader

Jenkinsfile_CNP
=> revert removing infra 

charts/sscs-case-loader/values.preview.template.yaml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJobTest.java, src/main/java/uk/gov/hmcts/reform/sscs/config/CaseLoaderJobConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/job/CaseLoaderTasklet.java
https://portal.azure.com#@531ff96d-0ae9-462a-8d2d-bec7c0b42082/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F1c4f0704-a29e-403d-b719-b90c34ef14c9%2FresourceGroups%2Fsscs-aat%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fsscs-aat%22%7D%5D%7D/query/H4sIAAAAAAAAAyspSkxOLeaqUSjPSC1KVUjOyS9NiQ%2FKz0n1zCsuScxLTlWwtVUqLk4u1k1OLE7VzclPTEkt0i0o0jU1N9HNyk%2FSNckrSilX4gIA%2BO9660gAAAA%3D/isQueryBase64Compressed/true/timespanInIsoFormat/P1D
```
[ ] Yes
[x] No
```
=> fix appinsights

src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java
=> sscs-6940 close the app at then

src/main/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJob.java, src/main/java/uk/gov/hmcts/reform/sscs/util/CaseLoaderTimerTask.java, src/test/java/uk/gov/hmcts/reform/sscs/util/CaseLoaderTimerTaskTest.java
=> Case loader sftp runnable thread closing fix

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
https://tools.hmcts.net/jira/browse/SSCS-7125
=> SSCS-7125 Do not process appeal received event for digital cases

src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapter.java
=> Case loader sftp runnable tread closing fix

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseRetryAndRecoveryTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java
=> SSCS-7140 Update AirLookup to v10

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
=> Sscs 7145 sscs 7223 venue airlookup changes

build.gradle
=> SSCS-7348 Reference data – Amendment to SSCS venue data Date TBC

build.gradle
=> SSCS-7550: New AirLookup

.github/renovate.json, build.gradle, charts/sscs-case-loader/Chart.yaml, charts/sscs-case-loader/requirements.yaml
SSCS-7568 
- Upgrade springboot to 2.3.x
- Upgrade Java Chart
- Add resonate.json
=> SSCS-7568 - Upgrade springboot to 2.3.x

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
=> SSCS-7708 Reference data – Amendment to SSCS venue data Date 23-06-20

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJobTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpc.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpcTest.java
https://tools.hmcts.net/jira/browse/SSCS-7535
```
[ ] Yes
[X] No
```
=> SSCS-7535 Case Loader handle isScottish on case update

audit.json
=> updated urls

audit.json
=> sscs-7911-updated urls of fix nightly job

build.gradle
SSCS-7309 - Set 'Previous State' field when case moves to dormant
=> SSCS-7309 - Set 'Previous State' field when case moves to dormant

Jenkinsfile_nightly
enable functional tests on nightly test build
=> enable functional tests on nightly test build

Jenkinsfile_nightly
Run functional tests at securityscan phase on Jenkins nightly test build
=> Run functional tests at securityscan phase on Jenkins nightly test build

build.gradle, dependency-check-suppressions.xml
SSCS-7806 - Processing documents for reinstatement requests
=> SSCS-7806 - Processing documents for reinstatement requests

dependency-check-suppressions.xml
=> Suppress tomcat dependency

security.sh
=> updated config for security scan

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseRefRetryAndRecoverTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseRefTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilder.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java
https://tools.hmcts.net/jira/browse/SSCS-8330
=> SSCS-8330 Move to Elastic Search

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/predeploy/ProcessCaseFileSetup.java, src/e2e/resources/SSCS_CcdCases_Delta_2018-07-09-12-34-56.xml, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/MultipleCaseFoundException.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
=> Sscs 8383 case loader fix

dependency-check-suppressions.xml
suppress for tests
```
[ ] Yes
[x] No
```
=> Fix for nightly tests

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilder.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java
=> Sscs 8038 retry idam

build.gradle
=> Fix dependency check failure

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java, src/test/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
=> Sscs 8514 caseloader sonarfix

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseData.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdProcessingVenue.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdProcessingVenueTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-8506
=> SSCS-8506 Update processing venue

build.gradle
=> Sscs 8607 illegal argument exception fix

build.gradle
=> Sscs 8722 sscsdocument sorting

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java
SSCS-8684 - Upgrade Idam Client Only
=> SSCS-8684 - Upgrade Idam Client Only

src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/PostcodeCaseFileTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/ProcessCaseFileTest.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/data/AbstractCaseFileTestData.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/data/PostcodeCaseFileTestData.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/data/ProcessCaseFileTestData.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/predeploy/PreDeployableTestData.java, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/predeploy/ProcessCaseFileSetup.java, src/e2e/java/uk/gov/hmcts/reform/tools/utils/CaseIdMapUtils.java, src/e2e/resources/SSCS_CcdCases_Delta_2021-02-23-12-00-00.xml
https://tools.hmcts.net/jira/browse/SSCS-8451
```
[ ] Yes
[ ] No
```
=> SSCS-8451:setting up automated regression test suite for caseloader service

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/TransformationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderBase.java, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java
=> Sscs 8639 cs amendpostponedlogic

build.gradle
fix cve
```
[ ] Yes
[x] No
```
=> cve-2021-22112

build.gradle
=> Fix dependency failures

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateSubscription.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateSubscriptionTest.java
=> Sscs 8720 incorrect remove email

src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-8880
Added DLA benefit type
```
[ ] Yes
[x] No
```
=> sscs 8880 added DLA as benefit type

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-8895
=> Sscs 8895 carers allowance

build.gradle, src/e2e/java/uk/gov/hmcts/reform/sscs/functional/postdeploy/ProcessCaseFileTest.java, src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-8894
https://tools.hmcts.net/jira/browse/SSCS-9037
```
[X] Yes
[ ] No
```
=> SSCS-8894: Carer's Allowance - Airlookup, DWP addresses & Robot Configuration

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9031
=> SSCS-9031 Carers allowance camel case fix

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactory.java, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/refdata/ReferenceDataServiceTest.java
SSCS-8901 - Attendance Allowance - Map Caseloader to Attendance Allowance Benefit Code
=> SSCS-8901 - Attendance Allowance - Map Caseloader to Attendance Allowance Benefit Code

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Finsih off move to jitpack
```
[ ] Yes
[x] No
```
=> sscs 9066 update to jitpack

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Move to release
```
[ ] Yes
[x] No
```
=> sscs 9066 move to release

src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-8907
=> SSCS-8907 Add test to cover bereavement benefit

build.gradle
SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
=> SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-8843
```
[ ] Yes
[ ] No
```
=> SSCS-8843: IIDB - Set Benefit Code to 067

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java
https://tools.hmcts.net/jira/browse/SSCS-9305
=> SSCS-9305 Refactor after moving deprecated fields

build.gradle
updated common with social fund benefit type
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9061](url)
=> SSCS-9061-updated common with social fund benefit type

build.gradle
SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer
=> SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
added assertions to ref data factory test
Jira: [https://tools.hmcts.net/jira/browse/SSCS-8927](url)
=> SSCS-8927- added assertions to ref data factory test

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java
https://tools.hmcts.net/jira/browse/SSCS-9191
fix postponements
```
[ ] Yes
[x] No
```
=> Sscs 9191 postponements

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-9381
The changes are in this PR but the same are implemented on nightly branch
```
[ ] Yes
[x ] No
```
=> SSCS-9381: Enable fortify scan for nightly build

build.gradle
SSCS-9341 - BenefitType not found
=> SSCS-9341 - BenefitType not found

src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java
https://tools.hmcts.net/jira/browse/SSCS-9490
Stop processing void cases
```
[ ] Yes
[x] No
```
=> sscs 9490 added  check for a void state

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9429
=> SSCS-9429 Deserialize case type id

dependency-check-suppressions.xml
=> Suppress spring dependency check until version upgraded

dependency-check-suppressions.xml
CVE-2021-22096 issue fix
```
[ ] Yes
[ x] No
```
=> CVE-2021-22096 fix

dependency-check-suppressions.xml
=> suppress h2 warning

docker/sftp/data/incoming/SSCS_Extract_Delta_SmokeTest_2022-01-13-03-12-52.xml
=> update file name

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-9902
```
[ ] Yes
[ ] No
```
=> SSCS-9902: Location data – Update airlookup to v15

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10132
```
[ ] Yes
[X] No
```
=> surpress dependency

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
https://tools.hmcts.net/jira/browse/SSCS-10070
update sscs-common version
```
[ ] Yes
[ ] No
```
=> update sscs-common version

charts/sscs-case-loader/Chart.yaml, dependency-check-suppressions.xml
=> SSCS-10280: Supress CVE warnings

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10297
```
[ ] Yes
[X] No
```
=> SSCS-10297: suppressing dependencies

build.gradle
=> Upgrade commons

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10387
```
[ ] Yes
[x] No
```
=> SSCS-10387 Update Commons

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10434
```
[ ] Yes
[X] No
```
=> SSCS-10434 Update Spring Core

build.gradle, dependency-check-suppressions.xml, src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataRepositoryTest.java
https://tools.hmcts.net/jira/browse/SSCS-10388
```
[x] Yes
[ ] No
```
=> SSCS-10388 Update Commons

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10503
```
[ ] Yes
[X] No
```
=> suppressing dependency

Jenkinsfile_nightly
=> Disable fortify scan in nightly

build.gradle, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10245
Update sscs common version
```
[ ] Yes
[ ] No
```
=> sscs-10245 update sscs common version

build.gradle
=> SSCS-10552-Tomcat-Upgrade: upgrade tomcat to 10.1.0-M15

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10561
```
[ ] Yes
[X] No
```
=> SSCS-10561: upgrading build.gradle

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10445
```
[ ] Yes
[x] No
```
=> SSCS-10445 Commons Bump

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10746
```
[ ] Yes
[ ] No
```
=> SSCS-10746-fix-cve

dependency-check-suppressions.xml
=> update extension date

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```
=> SSCS-10805-update-jar-version

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJobTest.java
https://tools.hmcts.net/jira/browse/SSCS-10773
Commons bumo
```
[ ] Yes
[ x] No
```
=> SSCS-10773: Update commons version

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[ ] No
```
=> sscs-9874 common version update

build.gradle, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```
=> SSCS-10882 Fixing Conflicting IDs

build.gradle, dependency-check-suppressions.xml
SSCS-10907
Update of snakeyaml library (was: suppression of not-applicable vulnerability)
```
[ ] Yes
[x] No
```
=> SSCS-10907 Long-term snakeyaml suppression

build.gradle, dependency-check-suppressions.xml
=> SSCS-10928 | Revert commons back to version that previously worked

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```
=> SSCS-10985 CVE Fix Commons Bump

build.gradle, dependency-check-suppressions.xml
CVE-2022-42252
```
[ ] Yes
[ x ] No
```
=> tomcat to 10.1.1

Dockerfile, build.gradle, charts/sscs-case-loader/Chart.yaml, dependency-check-suppressions.xml
=>  dockerfile tag change

build.gradle, dependency-check-suppressions.xml
CVE fix
```
[ ] Yes
[x] No
```
=> CVE-06.04.23

build.gradle
=> dependencySet(group: 'org.springframework', version: '5.2.24.RELEASE')

build.gradle
CVE Fix 30.05.2023 - Tomcat 10.1.9
```
[ ] Yes
[x] No
```
=> CVE Fix 30.05.2023 - Tomcat 10.1.9

build.gradle, charts/sscs-case-loader/Chart.yaml, dependency-check-suppressions.xml, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseIdRetryAndRecoverTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseIdTest.java, src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdServiceRetryAndRecoverTest.java
CVE Fix 01.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix 01.06.2023

dependency-check-suppressions.xml
CVE Suppression - 12.06.2023
```
[ ] Yes
[x] No
```
=> CVE Suppression - 12.06.2023

Jenkinsfile_nightly
=> SSCS-11771-Fortify-security-issue

Jenkinsfile_nightly, dependency-check-suppressions.xml
CVE Fix - 27.06.23
```
[ ] Yes
[x] No
```
=> CVEFix - 27.06.23

build.gradle, dependency-check-suppressions.xml
CVE Fix - 03.07.23
```
[ ] Yes
[x] No
```
=> CVE Fix - 03.07.23

build.gradle
CVE Fix - 31.07.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 31.07.2023

build.gradle
=> Revert commons to 4.26.2

build.gradle
=> revert caseloader -1

.gitignore, Dockerfile, build.gradle, charts/sscs-case-loader/Chart.yaml, charts/sscs-case-loader/values.yaml, lib/AI-Agent.xml, lib/applicationinsights.json
=> revert app insights

build.gradle
=> revert sscs commons from 4.26.4 to 4.26.2

build.gradle, dependency-check-suppressions.xml, src/e2e/java/uk/gov/hmcts/reform/tools/utils/CaseIdMapUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapterTest.java
I compared dependency versions between this and https://github.com/hmcts/sscs-tribunals-case-api/blob/master/build.gradle using:
```
./gradlew -q dependencies --configuration runtimeClasspath
```
I noticed a lot of inconsistencies across versions.
I don't know exactly what fixed it although I suspect it's the dependency management on openfeign.
I would rather not look for a minimal fix as all these fixes should be useful I think.
=> Fixup gradle file

dependency-check-suppressions.xml, src/main/resources/application.yaml
=> SSCSCI-12: suppress known CVEs

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-619
Revert commons version so caseloader will run
=> SSCSCI-619 - Revert Commons Version

dependency-check-suppressions.xml
=> SSCS - Update Suppressions

dependency-check-suppressions.xml
update suppressions
```
[ ] Yes
[x] No
```
=> CVE Fix - 22.01.2024

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-488
- exclude service class to fix sonar failure, while investigating test misconfiguration
```
[ ] Yes
[X] No
```
=> SSCSCI-488: exclude service class due to test misconfig

src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
https://tools.hmcts.net/jira/browse/SSCSCI-654
Log details in exception when case fails to update to validation error
=> SSCSCI-654 - Log details of validation errors

src/main/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJob.java, src/main/java/uk/gov/hmcts/reform/sscs/services/DataMigrationService.java, src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java, src/main/java/uk/gov/hmcts/reform/sscs/util/MigrationDataEncoderApp.java, src/main/java/uk/gov/hmcts/reform/sscs/util/MigrationStringUtils.java, src/test/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJobTest.java, src/test/java/uk/gov/hmcts/reform/sscs/services/DataMigrationServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/MigrationStringUtilsTest.java
- https://tools.hmcts.net/jira/browse/SSCSCI-677
- stop NPE when language is null
```
[ ] Yes
[X] No
```
=> SSCISCI-677: stop NPE when language is null

dependency-check-suppressions.xml
Updated expiry date in suppression file
=> Update suppression date

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-828
Upgraded snakeyaml to fix CVE-2022-1471
=> Upgraded snakeyaml

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-874
Updated suppression date
```
[ ] Yes
[x] No
```
=> SSCSCI-874 Update suppression date

build.gradle, charts/sscs-case-loader/Chart.yaml, charts/sscs-case-loader/values.yaml, src/main/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJob.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJobTest.java
https://tools.hmcts.net/jira/browse/SSCSCI-870
Update case management location in processing venue migration job
```
[ ] Yes
[ ] No
```
=> SSCSCI-870: update venue migration

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-923
- Upgrade sscs-common, update Reading venue address
```
[ ] Yes
[X] No
```
=> Upgrade sscs-common, update Reading venue address

dependency-check-suppressions.xml
Updated suppression date
```
[ ] Yes
[x] No
```
=> SSCSCI Suppression date update

build.gradle, config/owasp/suppressions.xml
See [SSCSCI-995](https://tools.hmcts.net/jira/browse/SSCSCI-995)
Jackson bump
sscs-common bump
Added versions variable to gradle
=> SSCSCI-995-jackson-databind-bump

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1185
=> Bump common to latest version(include enum changes for add hearing outcome)

build.gradle
=> SSCSCI-1345 commons bump

build.gradle
https://tools.hmcts.net/jira/browse/SSCSSI-247
Updated sscs commons
```
[x ] Yes
[ ] No
```
=> SSCSSI-247: Update to sscs commons

build.gradle
=> SSCSCI-1347 commons bump

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1547
```
[ ] Yes
[ ] No
```
=> SSCSCI-1547 commons bump

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1205
```
[ ] Yes
[ ] No
```
=> SSCSCI-1205: update sscs-common

build.gradle
=> Sscsci 1536: Bump commons

build.gradle
=> SSCSCI-1531

build.gradle
=> SSCSCI-1607 Test sb3 sscs-commons

build.gradle
=> SSCSCI-1563 / SSCSCI-1439 commons bump

build.gradle
Reverts hmcts/sscs-case-loader#1573
=> Revert "commons bump"

build.gradle
=> SSCSCI-1778

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1747
- test common elastic search changes
```
[ ] Yes
[x] No
```
=> test common elastic search changes

build.gradle
=> common bump

charts/sscs-case-loader/Chart.yaml
See [SSCSCI-1787](https://tools.hmcts.net/jira/browse/SSCSCI-1787)
| Library | Change |
| --- | --- |
| [chart-job](https://github.com/hmcts/chart-job) | `2.1.2` -> `2.2.0` |
The chart update required repository update to `oci://hmctspublic.azurecr.io/helm`
```
[ ] Yes
[x] No
```
=> SSCSCI-1787: Helm chart update

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1719
```
[ ] Yes
[ ] No
```
=> SSCSCI-1719 commons bump

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1832
- remove duplicate outdated commons-io dependency
```
[ ] Yes
[x] No
```
=> SSCSCI-1832: remove duplicate outdated commons-io dep

build.gradle
=> commons pointing

build.gradle
See [SSCSCI-1862](https://tools.hmcts.net/jira/browse/SSCSCI-1862)
sscs-common bump to 6.2.8
```
[ ] Yes
[x] No
```
=> SSCSCI-1862: sscs-common bump

build.gradle
Spring framework bump to 5.3.33 to resolve CVE-2024-22259
```
[ ] Yes
[x] No
```
=> SSCSCI: dependency check fix

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1877
```
[ ] Yes
[x] No
```
=> SSCSCI-1877 - update commons

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1945
- upgrade to secs-common 6.3.7
```
[ ] Yes
[x] No
```
=> upgrade to secs-common 6.3.7

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-1978
- Upgrade sscs-common to v6.3.8
```
[ ] Yes
[x] No
```
=> Upgrade sscs-common to v6.3.8

build.gradle
Library updates
| Name | Change |
| --- | --- |
| [org.yaml:snakeyaml](https://bitbucket.org/snakeyaml/snakeyaml/src/master/ ) | `2.0` -> `2.4` |
| [org.apache.commons:commons-text](https://commons.apache.org/proper/commons-text/) | `1.10.0` -> `1.14.0` |
| [org.apache.commons:commons-lang3](https://commons.apache.org/proper/commons-lang/) | `3.12.0` -> `3.18.0` |
Fixes CVE-2025-48924
Reason for Suppression: Needs a Spring 3 upgrade
Mitigating Factors: application is not client faced
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
```
[ ] Yes
[x] No
```
=> SSCSCI dependency check error fix

config/owasp/suppressions.xml
Extend suppression date by a month
CVE-2024-38820 requires update to Spring Boot 3 
```
[ ] Yes
[x] No
```
=> SSCS-CI: Update suppression date
